services:
  api:
    build:
      context: .
      dockerfile: scriptsPython/Dockerfile
    container_name: api-backend
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: QuizDb
      DB_USER: postgres
      DB_PASSWORD: "123456"
      DB_PORT: "5432"
    ports:
      - "192.168.100.9:8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - api
    ports:
      - "192.168.100.9:5173:80"
